[package]
name = "Mori"
version = "1.0.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
byteorder = "1.5.0"
rand = "0.8.5"
ureq = { version = "2.10.1", features = ["cookies", "json", "socks-proxy"] }
urlencoding = "2.1.3"
rusty_enet = { git = "https://github.com/CLOEI/rusty_enet.git" }
paris = { version = "1.5", features = ["timestamps", "macros", "no_logger"] }
sha2 = "0.10.8"
md5 = "0.7.0"
hex = "0.4.3"
regex = "1.10.6"
serde_json = "1.0.125"
base64 = "0.22.1"
serde = { version = "1.0.208", features = ["derive"] }
gtworld-r = { git = "https://github.com/CLOEI/gtworld-r.git" }
serde_repr = "0.1.19"
gtitem-r = { git = "https://github.com/CLOEI/gtitem-r.git" }
eframe = { version = "0.30.0" }
egui_extras = { version = "0.30.0", features = ["svg", "syntect"] }
egui = "0.30.0"
socks = "0.3.4"
thiserror = "2.0.9"
mlua = { version = "0.10.1", features = ["lua54", "vendored", "send"] }
wait-timeout = "0.2.0"
rust-otp = "2.0.0"
egui-phosphor = { version = "0.8", features = ["fill"] }
flate2 = "1.0.34"
rttex = { git = "https://github.com/CLOEI/rttex" }
dirs = "5.0.1"
image = "0.25.5"

