struct LoginInfo {
    tank_id_name: String,
    tank_id_pass: String,
    requested_name: String,
    f: String,
    protocol: String,
    game_version: String,
    fz: String,
    lmode: String,
    cbits: String,
    player_age: String,
    gdpr: String,
    category: String,
    total_playtime: String,
    klv: String,
    hash2: String,
    meta: String,
    fhash: String,
    rid: String,
    platform_id: String,
    device_version: String,
    country: String,
    hash: String,
    mac: String,
    wk: String,
    zf: String,
}
