/*



 * Auto-generated by Frida. Please modify to match the signature of sub_be7d70.



 * This stub is currently auto-generated from manpages when available.



 *



 * For full API reference, see: https://frida.re/docs/javascript-api/



 */






// 0xBE7D70
defineHandler({



  onEnter(log, args, state) {



    const packet_type = args[0]



    const data = args[1]



    const data_size = args[2]



    const extra_data = args[3]



    const flag = args[5]



    const extraDataSize = data.add(52).readU32();







    log(`[PACKET] Type: ${packet_type} | Size: ${data_size} | Flags: 0x${flag.toString(16)} | extra_data_size: ${extraDataSize}`);



  },







  onLeave(log, retval, state) {



  }



});



