/*
 * Auto-generated by Frida. Please modify to match the signature of sub_be7c50.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */
// 0xBE7C50
defineHandler({
  onEnter(log, args, state) {
    const packet_type = args[0]
    const data_ptr = args[1]
    var size = data_ptr.add(16).readU64().toNumber();
    var capacity = data_ptr.add(24).readU64().toNumber();
    var data_location = (capacity <= 15) ? data_ptr : data_ptr.readPointer();

    log(`[PACKET STRING] Type: ${packet_type} | data: ${data_location.readUtf8String()}`);


  },

  onLeave(log, retval, state) {
  }
});
