/*
 * Auto-generated by Frida. Please modify to match the signature of sub_be7d10.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    const data = args[0]
    log(`[PACKET STRING] Data: ${data.toString()}`);

  },

  onLeave(log, retval, state) {
  }
});
